### ISSUE TITLE
Issues with Wraith Corporation megawads

### ISSUE THREAD

**Issue by Star-X555** [vanessakindell/wadsmoosh-plus#10]
Log included.

I dunno if this will affect the final product, but 128 errors over missing files feels like it could go spectacularly wrong.
[wadsmoosh.log](https://github.com/vanessakindell/wadsmoosh-plus/files/15411595/wadsmoosh.log)

**Comment by Pointing8422** [comment]
+1, I also have this problem, when I played the Hell to Pay levels, the enemies and weapons are from Doom 2 and no the replacements, and some assets in the environment are missing.

**Comment by Zerodarkage** [comment]
Wait! I have zero problems! Look! (No errors at all!)
[wadsmoosh.log](https://github.com/user-attachments/files/16667076/wadsmoosh.log)

**Comment by Pointing8422** [comment]
@Zerodarkage What is the MD5 and SHA1 sum of your wad? Maybe our file is corrupted? Mine is:
-MD5: ba4d2564c72f7ec963be2f02c3c3e5f5
-SHA1: 3a261acd34c09585d0a7fe61e16913e96f7eb8b0

**Comment by Zerodarkage** [comment]
@Pointing8422 HELL2PAY.WAD
-MD5: BFABD79EC1207CCD59569274EDAB9FD1
-DE4216E73F549CF464176A1ECFC3C0EC29BE1091

**Comment by Pointing8422** [comment]
I was using it too, but I didn't install it on dos, after install it I get another wad and I didn't have more errors on my log. Still, the weapons on Hell to Pay are still from Doom 2 and not from the wad (BFG instead of the red trident or plasma gun instead of the blue trident), but now I get other assets like music and walls, so is better than before.

**Comment by Zerodarkage** [comment]
There is a dehacked patch on the original to change graphics and some other things!

**Comment by vanessakindell** [comment]
The problem is the weird way in which these expansions wads are created. They ship with a tool that generates the wads by merging their files with the doom2.wad file supplied by retail Doom 2. I'm not entirely sure how to fix t his. If anyone has guidance I'd be happy to implement it.

**Comment by vanessakindell** [comment]
PerdGate.wad
MD5: 598ffb6a1ac0844af6e1f19a8870f5f5
SHA1: 3e8d6e87df771cb4c272ffd086505d10d970968b

hell2pay.wad
MD5: a5f849e7461f37a0837788e28acdfeb2
SHA1: a8ea21198527ae54bc437c1e0d256d0cf51accfd

**Comment by vanessakindell** [comment]
Fixed errors in dev branch. Will merge into main branch at next pull.

As for the assets that replace Doom 2's graphics, I'm gonna make a new issue for that and start a project for that as well.
