### ISSUE TITLE
Add Legacy of Rust Support

### ISSUE THREAD

**Issue by PowerCD** [vanessakindell/wadsmoosh-plus#12]

**Comment by vanessakindell** [comment]
This is something I'm working on but it's gonna take awhile because I have to convert the ID24 format to GZDoom format. I'll push what I have to the dev branch when I'm far enough along to justify it.

**Comment by staticnation** [comment]
> This is something I'm working on but it's gonna take awhile because I have to convert the ID24 format to GZDoom format. I've created a project for this and I've created a lordev branch for this project.

@vanessakindell Ive done most of the work already, but the DEHACKED/DECOHACK stuff needs to be converted to zscript (this is outside of my ability) so you dont get legacy of rust weapons in other episodes etc. Hopefully this will save you some work.

https://github.com/staticnation/wadsmoosh-plus
