### ISSUE TITLE
[Request] Merge with WadFusion by Owlet

### ISSUE THREAD

**Issue by mattbratt11** [vanessakindell/wadsmoosh-plus#18]
I heard that Owlet has released yet another WadSmoosh Fork called "WadFusion" which contained support for Legacy of Rust, ID Deathmatch Maps, and the Rejects of Master Levels.

Does the WadSmoosh-plus contain most of that along with Unofficial Final Doom Sequels (PL2, PRCP, TNTR, TNT2D, etc.), BlueFireZ88's Lost Episodes of Doom 2.0 Patch with 4 Episodes (JPTR_V40.wad, LOST.WAD), Doom Zero (Unofficial 3rd part of Final Doom), etc.?

**Comment by vanessakindell** [comment]
Several of those are in the dev branch including today I just added Lost Episodes of Doom. If you switch to the dev branch and check the readme file it has a list of everything it supports. I do plan to add support for Legacy of Rust but I'm still working on it. Looking at the source of WadFusion is going to help with this effort so thanks for letting me know about it.

If you'd like me to add support for additional episodes, create new issues with each request separately so I can work on them individually and keep track of everything and accept/reject the proposal on an individual basis.

**Comment by vanessakindell** [comment]
Several of those are in the dev branch including today I just added Lost Episodes of Doom. If you switch to the dev branch and check the readme file it has a list of everything it supports. I do plan to add support for Legacy of Rust but I'm still working on it. Looking at the source of WadFusion is going to help with this effort so thanks for letting me know about it.

If you'd like me to add support for additional episodes, create new issues with each request separately so I can work on them individually and keep track of everything and accept/reject the proposal on an individual basis.
